/** Target finger extension vector [thumb, index, middle, ring, pinky] in 0–1. WLASL-inspired labels for interview context. */
export type SignPattern = {
  word: string;
  /** Ideal extended state per finger (0 folded, 1 extended) */
  pattern: [number, number, number, number, number];
};

/** 50+ common interview-relevant signs — heuristic patterns for demo matching */
export const ASL_VOCABULARY: SignPattern[] = [
  /** Starter Pack - Extremely Simple Signs */
  { word: 'one', pattern: [0, 1, 0, 0, 0] },
  { word: 'two', pattern: [0, 1, 1, 0, 0] },
  { word: 'three', pattern: [1, 1, 1, 0, 0] },
  { word: 'four', pattern: [0, 1, 1, 1, 1] },
  { word: 'five', pattern: [1, 1, 1, 1, 1] },
  { word: 'L shape', pattern: [1, 1, 0, 0, 0] },
  { word: 'V shape', pattern: [0, 1, 1, 0, 0] },
  { word: 'OK', pattern: [0, 0, 1, 1, 1] },
  { word: 'I Love You', pattern: [1, 1, 0, 0, 1] },
  { word: 'Hello', pattern: [1, 1, 1, 1, 1] },

  /** General Vocabulary */
  { word: 'yes', pattern: [0, 0, 0, 0, 0] }, // Fist (all folded)
  { word: 'no', pattern: [0, 1, 1, 0, 0] },
  { word: 'understand', pattern: [0, 1, 0, 1, 0] },
  { word: 'please', pattern: [1, 0, 1, 0, 0] },
  { word: 'name', pattern: [0, 1, 1, 1, 1] },
  { word: 'work', pattern: [0, 0, 0, 1, 0] },
  { word: 'experience', pattern: [0, 1, 1, 0, 1] },
  { word: 'help', pattern: [1, 1, 1, 0, 0] },
  { word: 'learn', pattern: [0, 1, 0, 0, 1] },
  { word: 'team', pattern: [0, 0, 1, 1, 0] },
  { word: 'good', pattern: [1, 0, 0, 1, 0] },
  { word: 'bad', pattern: [0, 0, 0, 0, 1] },
  { word: 'ready', pattern: [1, 1, 0, 1, 0] },
  { word: 'question', pattern: [0, 1, 1, 1, 0] },
  { word: 'answer', pattern: [1, 0, 1, 1, 0] },
  { word: 'time', pattern: [0, 1, 0, 0, 0] },
  { word: 'wait', pattern: [1, 0, 0, 1, 1] },
  { word: 'sorry', pattern: [1, 1, 1, 1, 0] },
  { word: 'agree', pattern: [0, 0, 1, 0, 1] },
  { word: 'need', pattern: [1, 1, 0, 0, 1] },
  { word: 'know', pattern: [1, 0, 1, 0, 1] },
  { word: 'think', pattern: [0, 1, 1, 0, 0] },
  { word: 'feel', pattern: [0, 0, 1, 1, 1] },
  { word: 'want', pattern: [1, 1, 1, 0, 1] },
  { word: 'can', pattern: [1, 0, 0, 0, 0] },
  { word: 'cannot', pattern: [0, 1, 0, 1, 1] },
  { word: 'will', pattern: [0, 0, 0, 1, 1] },
  { word: 'done', pattern: [1, 1, 1, 1, 1] },
  { word: 'more', pattern: [0, 1, 1, 1, 1] },
  { word: 'less', pattern: [1, 1, 0, 1, 1] },
  { word: 'start', pattern: [0, 1, 1, 0, 0] },
  { word: 'stop', pattern: [0, 0, 0, 0, 0] },
  { word: 'again', pattern: [1, 1, 1, 0, 0] },
  { word: 'number', pattern: [0, 1, 0, 1, 0] },
  { word: 'year', pattern: [0, 0, 1, 0, 0] },
  { word: 'month', pattern: [0, 1, 1, 0, 1] },
  { word: 'day', pattern: [1, 0, 1, 1, 1] },
  { word: 'skill', pattern: [0, 0, 1, 0, 1] },
  { word: 'company', pattern: [1, 0, 1, 0, 0] },
  { word: 'role', pattern: [0, 0, 1, 1, 0] },
  { word: 'interview', pattern: [1, 0, 0, 1, 0] },
  { word: 'sign', pattern: [0, 1, 0, 0, 1] },
  { word: 'language', pattern: [0, 1, 0, 1, 1] },
  { word: 'translate', pattern: [1, 1, 0, 1, 1] },
  { word: 'communicate', pattern: [1, 0, 1, 1, 0] },
  { word: 'different', pattern: [0, 0, 0, 1, 0] },
  { word: 'same', pattern: [0, 0, 1, 0, 0] },
  { word: 'practice', pattern: [1, 1, 0, 0, 0] },
  { word: 'project', pattern: [0, 1, 0, 0, 0] },
  { word: 'goal', pattern: [1, 0, 0, 0, 1] },
  { word: 'problem', pattern: [0, 1, 0, 1, 0] },
  { word: 'solution', pattern: [1, 1, 1, 1, 0] },
  { word: 'leader', pattern: [0, 0, 0, 1, 1] },
  { word: 'culture', pattern: [0, 1, 1, 1, 0] },
  { word: 'remote', pattern: [1, 0, 0, 1, 1] },
  { word: 'office', pattern: [0, 0, 1, 1, 1] },
  { word: 'salary', pattern: [1, 1, 0, 1, 0] },
  { word: 'benefits', pattern: [0, 1, 1, 0, 1] },
  { word: 'schedule', pattern: [1, 0, 1, 1, 1] },
];
