export type RoleKey =
  | 'Software Engineer'
  | 'Data Analyst'
  | 'Product Manager'
  | 'Marketing'
  | 'HR'
  | 'General';

const bank: Record<RoleKey, string[]> = {
  'Software Engineer': [
    'Tell me about a bug you fixed that made the product better.',
    'How do you test your code before it goes to production?',
    'Describe a time you had to learn a new framework quickly.',
    'How do you explain a technical idea to a non-technical teammate?',
    'What is something you automated to save time?',
    'How do you handle conflicting opinions in a code review?',
    'Tell me about a project where requirements changed mid-way.',
    'What is your approach to debugging a hard issue?',
    'How do you stay current with engineering best practices?',
    'Describe how you would design a simple rate limiter.',
    'What trade-offs do you consider when picking a database?',
    'Tell me about working with a tight deadline.',
    'How do you document decisions for your team?',
    'Describe a mistake you made and what you changed afterward.',
    'What does good teamwork look like on your ideal project?',
    'How do you measure if a feature was successful?',
    'Tell me about mentoring or helping a junior developer.',
    'What kind of technical debt have you paid down?',
    'How do you prioritize tasks when everything feels urgent?',
    'What draws you to this role and team?',
  ],
  'Data Analyst': [
    'Walk me through how you would check if a metric spike is real.',
    'Tell me about a dashboard stakeholders actually used.',
    'How do you communicate uncertainty in your analysis?',
    'Describe cleaning a messy dataset you received.',
    'What is your process for validating an A/B test result?',
    'How would you explain correlation vs causation to a marketer?',
    'Tell me about a time your analysis changed a decision.',
    'What tools do you use for SQL-heavy work and why?',
    'How do you detect outliers before modeling?',
    'Describe collaborating with an engineer on a pipeline.',
    'What is a KPI you think is often misunderstood?',
    'How do you document assumptions in an analysis?',
    'Tell me about balancing speed vs accuracy.',
    'What would you do if a stakeholder wanted a flawed metric?',
    'How do you learn the business context for a new domain?',
    'Describe presenting findings to executives.',
    'What is your approach to missing data?',
    'Tell me about a mistake in an analysis and how you fixed it.',
    'How do you prioritize ad-hoc requests?',
    'Why are you interested in analytics in this industry?',
  ],
  'Product Manager': [
    'Tell me how you decide what not to build.',
    'Describe discovery with users for a recent feature.',
    'How do you handle disagreement between design and engineering?',
    'What is your framework for prioritizing a backlog?',
    'Tell me about launching something that did not work.',
    'How do you define success before shipping?',
    'Describe working with a tight roadmap change.',
    'What signals tell you it is time to sunset a feature?',
    'How do you write a clear problem statement?',
    'Tell me about influencing without direct authority.',
    'What is your approach to stakeholder updates?',
    'How do you balance technical debt vs new features?',
    'Describe a time you said no to a powerful stakeholder.',
    'What product decisions are you most proud of?',
    'How do you incorporate accessibility into the roadmap?',
    'Tell me about a competitive threat you responded to.',
    'What habits help you stay customer-focused?',
    'How do you run effective retrospectives?',
    'Describe aligning multiple teams on one goal.',
    'Why this product area for your next role?',
  ],
  Marketing: [
    'Tell me about a campaign you ran end to end.',
    'How do you measure marketing ROI on a tight budget?',
    'Describe repositioning a product for a new audience.',
    'What channels performed best for you and why?',
    'Tell me about partnering with sales successfully.',
    'How do you test messaging before a full launch?',
    'Describe a brand risk you had to manage.',
    'What is your process for creative briefs?',
    'Tell me about a failed experiment and what you learned.',
    'How do you keep messaging consistent across teams?',
    'Describe using data to refine a funnel.',
    'What role does storytelling play in your work?',
    'Tell me about working under a short promotion deadline.',
    'How do you handle negative public feedback?',
    'What marketing trend do you think is overrated?',
    'Describe collaborating with product on a launch.',
    'Tell me about a stakeholder who was hard to win over.',
    'How do you prioritize channels with limited resources?',
    'What does ethical marketing mean to you?',
    'Why are you excited about marketing here?',
  ],
  HR: [
    'Tell me about improving an onboarding experience.',
    'How do you handle a sensitive employee relations issue?',
    'Describe designing a fair interview process.',
    'What metrics do you track for hiring quality?',
    'Tell me about influencing leaders on policy change.',
    'How do you support inclusion day to day?',
    'Describe mediating a conflict between two teammates.',
    'What is your approach to performance feedback?',
    'Tell me about a compliance challenge you navigated.',
    'How do you partner with managers on retention?',
    'Describe scaling recruiting during rapid growth.',
    'What makes a benefits package feel competitive?',
    'Tell me about a program you built from scratch.',
    'How do you communicate difficult news to staff?',
    'What is your stance on hybrid work policies?',
    'Describe improving diversity in a pipeline.',
    'Tell me about a time HR data changed a people decision.',
    'How do you stay calm during high-stress HR moments?',
    'What employee listening methods do you trust?',
    'Why do you want to grow your HR career here?',
  ],
  General: [
    'Tell me about yourself in two minutes.',
    'What is a strength you bring to teams?',
    'Describe a challenge you overcame at work.',
    'How do you handle tight deadlines?',
    'Tell me about feedback you implemented.',
    'Why are you looking for a new role now?',
    'Describe your ideal manager.',
    'How do you learn new skills?',
    'Tell me about a conflict you resolved.',
    'What accomplishment are you most proud of?',
    'How do you prioritize when everything is important?',
    'Describe a time you showed leadership.',
    'What motivates you day to day?',
    'Tell me about a mistake and how you recovered.',
    'How do you prepare for important meetings?',
    'Describe working with someone difficult.',
    'What questions do you have for us?',
    'How do you define success in this stage of your career?',
    'Tell me about a project you owned.',
    'What environment helps you do your best work?',
  ],
};

export function getOfflineQuestions(role: RoleKey): string[] {
  return [...bank[role]];
}

export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
